spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 1500
server:
  port: 8088
  error:
    include-exception: true
